// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGqcX0G_jVhMfrdnF4cdeTFcFNNpGTBk4',
    appId: '1:598636394876:web:859c10b9a5a43850b60cf9',
    messagingSenderId: '598636394876',
    projectId: 'my-awesome-project-b4aa8',
    authDomain: 'my-awesome-project-b4aa8.firebaseapp.com',
    storageBucket: 'my-awesome-project-b4aa8.firebasestorage.app',
    measurementId: 'G-E0D2N93418',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGqcX0G_jVhMfrdnF4cdeTFcFNNpGTBk4',
    appId: '1:598636394876:android:5714f9bef1f42472b60cf9',
    messagingSenderId: '598636394876',
    projectId: 'my-awesome-project-b4aa8',
    storageBucket: 'my-awesome-project-b4aa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqcX0G_jVhMfrdnF4cdeTFcFNNpGTBk4',
    appId: '1:598636394876:ios:ea21cec1bd045ef1b60cf9',
    messagingSenderId: '598636394876',
    projectId: 'my-awesome-project-b4aa8',
    storageBucket: 'my-awesome-project-b4aa8.firebasestorage.app',
    iosBundleId: 'com.example.flutterGoogleAnalyticsLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGqcX0G_jVhMfrdnF4cdeTFcFNNpGTBk4',
    appId: '1:598636394876:web:859c10b9a5a43850b60cf9',
    messagingSenderId: '598636394876',
    projectId: 'my-awesome-project-b4aa8',
    authDomain: 'my-awesome-project-b4aa8.firebaseapp.com',
    storageBucket: 'my-awesome-project-b4aa8.firebasestorage.app',
    measurementId: 'G-E0D2N93418',
    iosBundleId: 'com.example.flutterGoogleAnalyticsLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGqcX0G_jVhMfrdnF4cdeTFcFNNpGTBk4',
    appId: '1:598636394876:web:f555cfc0eac399d0b60cf9',
    messagingSenderId: '598636394876',
    projectId: 'my-awesome-project-b4aa8',
    authDomain: 'my-awesome-project-b4aa8.firebaseapp.com',
    storageBucket: 'my-awesome-project-b4aa8.firebasestorage.app',
    measurementId: 'G-E0D2N93418',
  );
}
